services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB:       lab6
      POSTGRES_USER:     postgres
      POSTGRES_PASSWORD: secret
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      MODE:        docker
      DB_HOST:     db
      DB_PORT:     5432
      DB_NAME:     lab6
      DB_USER:     postgres
      DB_PASSWORD: secret
    depends_on:
      db:
        condition: service_healthy

volumes:
  pgdata:
